### ISSUE TITLE
Test requirements and bug fixes during sprint ending 03/03/2022

### ISSUE THREAD

**Issue by tloubrieu-jpl** [NASA-PDS/system-i-n-t#20]
### Bug:
- [x] nasa-pds/harvest#75
- [x] nasa-pds/pds-registry-common#20
- [x] nasa-pds/registry-api#73

### Requirements:
- [x] nasa-pds/pds-api#66
- [x] nasa-pds/pds-api#153
- [x] nasa-pds/pds-registry-app#187
- [x] nasa-pds/pds-registry-app#208
- [x] pds-registry-app/issues/223
- [ ] ~~nasa-pds/pds-registry-app#230~~ (N/A to i&t, has a skip-i&t tag)
- [x] nasa-pds/pds4-information-model#341

**Comment by tloubrieu-jpl** [comment]
@viviant100 @gxtchen I completed this ticket with all the currently closed tickets for the current sprint. Thanks

**Comment by viviant100** [comment]
thank you @tloubrieu-jpl

**Comment by viviant100** [comment]
@tloubrieu-jpl  I removed https://github.com/NASA-PDS/pds-registry-app/issues/230 from the list since it has a skip-i&t tag.
