### ISSUE TITLE
B14.0 Delivery & Deployment Review (DDR)

### ISSUE THREAD

**Issue by jordanpadams** [NASA-PDS/system-i-n-t#47]
## 💡 Description

Fri 11/3/23 - Thu 11/30/23
- [x] Generate and Release Final Release Description Document (RDD)
- [x] Generate & Submit DDR Presentation
- [x] Release Test Report

**Comment by jordanpadams** [comment]
📆 October status: Wrapping up testing and beginning DDR prep.

**Comment by jordanpadams** [comment]
- https://pds-engineering.jpl.nasa.gov/file/b14.0.testrail_report_2514.20231112.pdf
- https://nasa-pds.github.io/releases/14.0/rdd.html
- https://pds-engineering.jpl.nasa.gov/file/pds_b14.0_ddr.wiki.20231117.pdf
- https://pds-engineering.jpl.nasa.gov/file/b14.0.testrail_report_2514.20231112.pdf
