### ISSUE TITLE
B15.0 Deployment and Release

### ISSUE THREAD

**Issue by jordanpadams** [NASA-PDS/system-i-n-t#53]
12/5/24
- [x] Deployment of Test Environment
- [x] Deployment of Production Environment
- [x] Webpage Updated
- [x] Release announcement to public

**Comment by jordanpadams** [comment]
@jshughes please deliver the new IM to @c-suh 

how have you gathered all the Discipline and Mission LDDs in the past?

**Comment by jordanpadams** [comment]
@c-suh we are a GO for release

**Comment by c-suh** [comment]
Waiting on 2 more documents (PDS4_PDS_DD_1N00.PDF and WebHelp documents for all LDDs) in order to complete webpage updates.

**Comment by jordanpadams** [comment]
📆 11/2024 status: Should go live on Monday 12/9

**Comment by c-suh** [comment]
Waiting on the last set of webhelp documents, which Steve said will be done soon. Hopefully by today or tomorrow, the webpages will be updated and operational.

**Comment by c-suh** [comment]
What is available has been made operational. Reopening this, however, for the last set of webhelp documents, which has not yet been delivered.

**Comment by c-suh** [comment]
The last set of WebHelp documents are on production! @jordanpadams I believe this release is ready to be announced to the public.

**Comment by jordanpadams** [comment]
Done. 🎉
